name: trying out search api

on:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Minimum required permission

    steps:
      - name: search
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X GET search/issues -f q='type:pr reviewed-by:cicirello' -f per_page='1' --cache '1h' 
          
#--json total_count --jq '.total_count'
          
#gh api -X GET search/commits -f q='author:cicirello' -f per_page='1' --cache '1h' --jq '.total_count'
