name: trying out search api

on:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Minimum required permission

    steps:
      - name: search
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X GET search/commits -f q='author:cicirello' -f per_page='1' --cache '1hr' --jq '.total_count'
