name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Run Python unit tests
      run: python3 -u -m unittest tests/tests.py

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile

    - name: Integration test
      id: integration
      uses: ./
      with:
        one-line: sub1/target/site/jacoco/jacoco.csv sub2/target/site/jacoco/jacoco.csv sub3/target/site/jacoco/jacoco.csv
        multiline-pipe: |
          sub1/target/site/jacoco/jacoco.csv
          sub2/target/site/jacoco/jacoco.csv
          sub3/target/site/jacoco/jacoco.csv
        multiline-greater: >
          sub1/target/site/jacoco/jacoco.csv
          sub2/target/site/jacoco/jacoco.csv
          sub3/target/site/jacoco/jacoco.csv

    - name: Output the outputs of the integration test of the action
      run: |
        echo "output-one = ${{ steps.integration.outputs.output-one }}"
        echo "output-two = ${{ steps.integration.outputs.output-two }}"

    - name: Verify integration test results
      run: python3 -u -m unittest tests/integration.py
